site_name: Metashade
site_description: Python EDSL for GPU shader code generation
site_url: https://metashade.dev
repo_url: https://github.com/metashade/metashade

theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/metashade/
      name: Metashade on PyPI
    - icon: fontawesome/brands/github
      link: https://github.com/metashade/metashade
      name: Metashade on GitHub
